# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET  = DbSync
CONFIG += release console 
CONFIG -= debug

QT += sql core

DESTDIR = ./App

LIBS += -L"."
DEPENDPATH += .

MOC_DIR     += tmp
OBJECTS_DIR += tmp
UI_DIR      += tmp
RCC_DIR     += tmp

SOURCES += ./main.cpp
